name: Verifica Formazioni Schierate

on:
  workflow_dispatch:
  schedule:
    # Esegue lo script due volte al giorno: alle 11:00 e alle 23:00 UTC
    # (circa mezzogiorno e mezzanotte in Italia)
    - cron: '0 11,23 * * *'

jobs:
  update-lineups-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests gspread google-auth-oauthlib

      - name: Esegui lo script di verifica formazioni
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} # Non usato qui, ma lo teniamo per coerenza
          SORARE_API_KEY: ${{ secrets.SORARE_API_KEY }}
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          USER_SLUG: ${{ secrets.USER_SLUG }}
        run: python check_lineups.py
