name: 3. Aggiorna Dati Carte

on:
  workflow_dispatch:
  schedule:
    # Esegui ogni 2 ore, tra le 7 e le 22 UTC
    - cron: '0 7-22/2 * * *'

permissions:
  contents: write

jobs:
  run-gestionale:
    runs-on: ubuntu-latest
    steps:
      # ... (steps identici al precedente)
      - name: Esegui lo script gestionale
        env:
          # ... (tutti i segreti necessari)
        run: python gestionale.py update_cards
      - name: Salva lo stato
        run: |
          # ... (logica di commit del file state.json)
